package com.yulmaso.k_notebook.storage.model

import androidx.room.Entity
import androidx.room.ForeignKey
import java.util.*

@Entity(
    tableName = "geotags", foreignKeys = [ForeignKey(
        entity = Note::class,
        parentColumns = arrayOf("id"),
        childColumns = arrayOf("id_note"),
        onDelete = ForeignKey.CASCADE)],
    primaryKeys = ["id_note", "id"] //TODO: need "id" to be autoGenerated!
)
class Geotag {
    var id_note: Int = 0
    var id: Int = 0
    var date: Calendar? = null
    var time: Calendar? = null
    var geolong: Float = 0F
    var geolat: Float = 0F
}